server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vhr?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  cache:
    cache-names: menus_cache

  mail:
    host: smtp.qq.com #邮箱服务器地址
    username: 639582921@qq.com  #用户名
    password: mvrtrggxijzgbcjj
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

mybatis:
  type-aliases-package: com.dajian.vhrserver.pojo
  mapper-locations: classpath:mapper/*.xml




